import Head from "next/head"
import Home from "../modules/home"
export default function HomePage() {

  return (
    <div>
      <Head>
        <title>OnRuf Business</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <Home  />
    </div>
  )
}

// export async function getServerSideProps({ query, locale }) {
//   try {
//     const {
//       data: { data: products },
//     } = await axios.get(`${process.env.REACT_APP_API_URL}/ListProductByBusinessAccountId`, {
//       ...headersJson,
//       params: {
//         currentPage: 1,
//         productFilter: 0,
//         lang: locale,
//         maxRows: 10,
//       },
//     })

//     const {
//       data: { data: orders },
//     } = await axios(`${process.env.REACT_APP_API_URL}/ListNewOrderForProvider?lang=${locale}`)

//     const {
//       data: { data: clients },
//     } = await axios(`${process.env.REACT_APP_API_URL}/GetListUserForProvider`)

//     return {
//       props: {
//         products,
//         orders,
//         clients,
//       },
//     }
//   } catch (e) {
//     console.log(e)
//     return {
//       props: {
//         products: [],
//         orders: [],
//         clients: [],
//         error: JSON.stringify(e),
//       },
//     }
//   }
// }
